---
- name: install epel
  command: amazon-linux-extras install -y epel
  when:
  - ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"


- name: install epel-release
  package:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat'
