---
- name: check epel
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_res


- name: install epel-release with amazon-linux-extras (amz2)
  command: amazon-linux-extras install -y epel
  when:
  - not epel_res.stat.exists
  - ansible_distribution == "Amazon" 
  - ansible_distribution_major_version == "2"


- name: install epel-release with yum (exclude [amz2])
  yum:
    name: epel-release
    state: present
    lock_timeout: 180
  when: 
  - ansible_os_family == 'RedHat'
  - not (ansible_distribution == "Amazon" and ansible_distribution_major_version == "2")
