- name: sssd-ldap
  yum: 
    name:
      - sssd
      - openldap-clients
      - sssd-ldap
      - authconfig
  lock_timeout: 180


- name: sssd start
  service: 
    name: sssd
    state: started
    enabled: yes
