---
- name: include vars from ansible os family
  include_vars: "{{ ansible_os_family }}.yml"

- name: install MySQL (yum)
  yum:
    name:
      - mysql-server
    state: present
    enablerepo:
      - mysql{{ mysqlver | join() }}-community
  when:
    - ansible_os_family == "RedHat"

      
    # mysql-server (8.0)
    # mysql-server-5.7
    # mysql-server-5.6 
- name: install MySQL (APT)
  apt:
    name:
      - mysql-server{{ "" if (mysqlver | join('.')) == "8.0" else "-" + (mysqlver | join('.')) }}
    state: present
  when:
    - ansible_os_family == "Debian"


- name: Enable service mysql and start
  service:
    name: "{{ mysqld }}"
    enabled: yes
    state: started
